# Generated by Django 4.2.3 on 2023-07-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='vimalathithan17@gmail.com', max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=10)),
                ('place_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=254)),
                ('availablity', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_data.pharmacy', to_field='place_id')),
            ],
        ),
    ]
